# device monitor config

run_time=1000
sample_interval=1

cpu_threshold=80
mem_threshold=85
temp_acpitz_1_threshold=70
temp_acpitz_2_threshold=70
temp_cpu_threshold=70

server_ip=127.0.0.1
server_port=8888

network_iface=enp1s0

log_file=logs/monitor.log